"""Pridėtas ivertinimas

Revision ID: cbeb70e62acf
Revises: 
Create Date: 2025-05-18 11:48:45.106153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbeb70e62acf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simptomai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ivertinimas', sa.Enum('teigiamas', 'neigiamas'), nullable=True))
        batch_op.alter_column('simptomas',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simptomai', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('simptomas',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('ivertinimas')

    # ### end Alembic commands ###
